### PR TITLE
fix: No such file on uncompress

### LINKED ISSUE #4: NotFound: No such file or directory
The `tar.uncompress()` function does not work because it attempts to write to a file that doesn't exist. I'll create a quick pull request once I find and fix the issue!

```
Check file:///Users/username/Downloads/test/mod.ts
error: Uncaught (in promise) NotFound: No such file or directory (os error 2)
    throw new ErrorClass(res.err.message);
          ^
    at processResponse (deno:core/core.js:213:11)
    at Object.jsonOpAsync (deno:core/core.js:231:12)
    at async Object.open (deno:runtime/js/30_files.js:45:17)
    at async Module.uncompress (https://deno.land/x/compress@v0.3.6/tar/mod.ts:13:18)
```

### PR DESCRIPTION
**Pull request by squarepear**
Ensure that the file exists before attempting to write to it.

fixes: #4

### CODE REVIEW

File: tar/mod.ts [hunk 1]
```diff
@@ -10,6 +10,7 @@ export async function uncompress(src: string, dest: string): Promise<void> {
       await ensureDir(filePath);
       continue;
     }
+    await ensureFile(filePath);
```
Comment (fuxingZhang) [inline tar/mod.ts:13]: The next line will create the file, so there is no need to ensure that the file exists

**Review by fuxingZhang — CHANGES_REQUESTED** [review]
await ensureDir(path.dirname(filePath));
